/*************************************************************************
 * File: personaldetails_4.cpp (CLOptions)
 * Copyright © 2017-2019 JCardenzana. All rights reserved.
 * 
 * Description:
 *      Demonstrates constructing a CLOptions object with predefined command
 *      line parameters for name, age, and weight. Notice there is no definition
 *      of the help text, as this is generated by default by CLOptions for the
 *      user.
 * 
 * Compile with:
 *      g++ -std=c++11 -I../include personaldetails_4.cpp -o personaldetails_4
 ************************************************************************/

#include <iostream>
#include <string>
#include "CLOptions.h"

// Print details of a given person
void PrintDetails(std::string name, int age, double weight)
{
    std::cout << "Name  : " << name << std::endl;
    std::cout << "Age   : " << age << std::endl;
    std::cout << "Weight: " << weight << std::endl;
    return ;
}

int main (int argc, char** argv)
{
    // Define the command line arguments
    CLOptions options ;
    options.AddStringParam("Name","This is the person's name.","") ;
    options.AddIntParam("Age","The age of the person in years",0) ;
    options.AddDoubleParam("Weight","The weight of the person in pounds.",0.0);
    
    // Parse the command line options
    if (options.ParseCommandLine(argc, argv)) {
        return 0 ;
    }
    
    // Print the persons details
    PrintDetails(options.AsString("Name"),
                 options.AsInt("Age"),
                 options.AsDouble("Weight")) ;
    
    return 0 ;
}